function hint(k, cmd)
%HINT  Progressive hints for the spectrum challenge problems.
%
%   hint(2)            prints the next hint for Challenge 2. The first
%                      time you call it you get hint 1. Call it again
%                      for hint 2, again for hint 3.
%   hint(2,'reset')    forgets where you were, so the next hint(2)
%                      starts again at hint 1.
%   hint               prints this summary.
%
%   There are three hints for every challenge and they get more and
%   more specific:
%      hint 1  a nudge - what to notice, or a different way to read
%              the question.
%      hint 2  names the method, or the exact thing to compare.
%      hint 3  the shape of the calculation, in enough detail that you
%              can type something and get moving.
%   No hint gives you the answer. When you have a number, test it with
%   selfcheck.
%
%   Your place in the hints is remembered until you close MATLAB or
%   type  clear functions.
%
%   Needs plain MATLAB. No toolbox.

persistent shown

n_challenges = 7;
n_hints      = 3;

if isempty(shown)
    shown = zeros(1, n_challenges);
end

if nargin < 1
    print_usage(shown, n_challenges, n_hints);
    return
end

if ~isnumeric(k) || ~isscalar(k) || ~isreal(k) || ~isfinite(k) || ...
        k < 1 || k > n_challenges || k ~= fix(k)
    fprintf('\n');
    fprintf('hint needs a challenge number from 1 to %d.\n', n_challenges);
    fprintf('For example:  hint(2)\n\n');
    return
end

if nargin >= 2
    if ~ischar(cmd) && ~isstring(cmd)
        fprintf('\nThe second argument must be the word reset, in quotes.\n');
        fprintf('For example:  hint(%d,''reset'')\n\n', k);
        return
    end
    if strcmpi(char(cmd), 'reset')
        shown(k) = 0;
        fprintf('\nHints for Challenge %d start again from the beginning.\n', k);
        fprintf('Type  hint(%d)  when you want the first one.\n\n', k);
        return
    end
    fprintf('\nThe only word hint understands is reset.\n');
    fprintf('For example:  hint(%d,''reset'')\n\n', k);
    return
end

if shown(k) >= n_hints
    fprintf('\n');
    fprintf('That was the last of the %d hints for Challenge %d.\n', n_hints, k);
    fprintf('From here it is your measurement to make.\n');
    fprintf('  - to read them all again:   hint(%d,''reset'')\n', k);
    fprintf('  - to test a number:         selfcheck(%d, your_value)\n\n', k);
    return
end

shown(k) = shown(k) + 1;
lines    = hint_text(k, shown(k));
left     = n_hints - shown(k);

fprintf('\n');
fprintf('------------------------------------------------------------\n');
fprintf('CHALLENGE %d   -   HINT %d of %d\n', k, shown(k), n_hints);
fprintf('------------------------------------------------------------\n');
for i = 1:numel(lines)
    fprintf('%s\n', lines{i});
end
fprintf('------------------------------------------------------------\n');
if left == 1
    fprintf('1 more hint. Type  hint(%d)  if you want it.\n', k);
elseif left > 1
    fprintf('%d more hints. Type  hint(%d)  if you want the next one.\n', left, k);
else
    fprintf('No hints left for this one. Test a number with selfcheck(%d, x).\n', k);
end
fprintf('\n');

end


function print_usage(shown, n_challenges, n_hints)
fprintf('\n');
fprintf('HINTS FOR THE CHALLENGE PROBLEMS\n');
fprintf('  hint(2)          next hint for Challenge 2\n');
fprintf('  hint(2,''reset'')  start Challenge 2 hints again\n');
fprintf('\n');
fprintf('There are %d hints for each challenge. They get more specific.\n', n_hints);
fprintf('None of them gives you the answer. Where you are so far:\n');
for k = 1:n_challenges
    fprintf('   Challenge %d : %d of %d hints read\n', k, shown(k), n_hints);
end
fprintf('\nWhen you have a number, test it with  selfcheck(k, value).\n\n');
end


function lines = hint_text(k, level)
% One cell of text lines per challenge and hint level.
lines = {'No hint is written for that one.'};

switch k

    case 1      % which antenna would actually work
        switch level
            case 1
                lines = { ...
                'Do part (a) first. It needs no new formula at all.', ...
                'Work out the wavelength of your highest station and of', ...
                'your lowest station, then a quarter of each. Put the two', ...
                'quarter-wave lengths side by side and ask how different', ...
                'they really are. That single comparison answers "do I', ...
                'need one antenna or six?" before you touch part (b).'};
            case 2
                lines = { ...
                'Part (b) is the two formulas in the file, used in order:', ...
                'first h divided by lambda, then Rr, then eta. Do that', ...
                'once for the 8.6 cm whip.', ...
                'Now do it again for a properly cut quarter wave - but', ...
                'for that one do NOT use the Rr formula. It only applies', ...
                'to whips MUCH shorter than a quarter wave. Use the value', ...
                'of Rr you were given for a quarter wave instead.', ...
                'The penalty is the difference between the two eta', ...
                'figures, in dB.'};
            case 3
                lines = { ...
                'The shape of the calculation, at 98.2 MHz:', ...
                '   lam    = 3e8/98.2e6;', ...
                '   h      = 0.086;', ...
                '   Rr     = 40*pi^2*(h/lam)^2;', ...
                '   eta    = 4*Rr*50/(Rr+50)^2;', ...
                '   eta_dB = 10*log10(eta);', ...
                'Then the same three lines with Rr = 36.5 for the quarter', ...
                'wave, and subtract one eta_dB from the other.', ...
                'Use 10*log10, not 20*log10: eta is already a power', ...
                'ratio, not a voltage.', ...
                'For part (c), take that dB number and subtract it from', ...
                'each "above the noise" figure you measured in Exercise 6.', ...
                'Then see which stations fall under about 15 dB.'};
        end

    case 2      % how short can the recording be
        switch level
            case 1
                lines = { ...
                'Parts (a) and (b) are not the same question.', ...
                'One asks whether you can tell two signals APART.', ...
                'The other asks whether you can SEE a weak signal at all.', ...
                'Decide which one you are answering before you write any', ...
                'code, and expect the two answers to be a long way apart.'};
            case 2
                lines = { ...
                'For (a): neighbouring FFT points are fs/N apart. Two', ...
                'peaks only count as two peaks if there is at least one', ...
                'point BETWEEN them that reads lower than both. Work out', ...
                'the n that gives you that, then plot it and check you', ...
                'can actually see the dip. Do not trust the arithmetic on', ...
                'its own.', ...
                'For (b): the noise floor MOVES when you change N, so a', ...
                'fixed threshold like -60 dB will lie to you. Compare', ...
                'each station with the noise floor of the same short', ...
                'piece of recording.'};
            case 3
                lines = { ...
                'For (a): the two closest stations are 200 kHz apart, so', ...
                'you need fs/n small enough that a point lands between', ...
                'them. Try a few values of n around that and look at the', ...
                'plot each time.', ...
                'For (b), the shape of it:', ...
                '   for n = [512 1024 2048 4096]', ...
                '      x  = iq(s+1:s+n);', ...
                '      S  = 20*log10(abs(fftshift(fft(x)))/n);', ...
                '      fM = (fc + (-n/2:n/2-1)*(fs/n))/1e6;', ...
                '      count how many of your six stations have a peak', ...
                '      at least 10 dB above median(S)', ...
                '   end', ...
                'Then run that whole loop again for three or four', ...
                'different values of s. Report the WORST count you saw,', ...
                'not the best.'};
        end

    case 3      % one of these is not a radio station
        switch level
            case 1
                lines = { ...
                'You are not being asked which peak looks odd. You are', ...
                'being asked for a TEST: a number you compute for all', ...
                'seven peaks that comes out clearly different for one of', ...
                'them.', ...
                'Start by listing the seven peak frequencies to the', ...
                'nearest Hz. One of them will already look suspicious.', ...
                'Suspicious is not proof.'};
            case 2
                lines = { ...
                'Three ideas that each turn into a number:', ...
                '  1. A transmitter carries information, so its power is', ...
                '     spread out around the carrier. Compare the power in', ...
                '     the whole 200 kHz channel with the power in the', ...
                '     single tallest point inside it.', ...
                '  2. Audio changes from moment to moment. Cut the', ...
                '     capture into eight blocks and see which peaks hold', ...
                '     still and which move about.', ...
                '  3. What is mean(iq)? Where in a spectrum does a', ...
                '     constant offset end up?', ...
                'Then find a test that FAILS. Comparing the two gain', ...
                'files is the obvious one to try.'};
            case 3
                lines = { ...
                'The decisive test, in two lines:', ...
                '   iq2 = iq - mean(iq);', ...
                '   S2  = 20*log10(abs(fftshift(fft(iq2)))/N);', ...
                'Now compare the height of all seven peaks in S_dB and in', ...
                'S2. Six of them will not move at all.', ...
                'Then compute 20*log10(abs(mean(iq))) and compare it with', ...
                'the height of the peak that did move. If those two', ...
                'numbers match, you have proved what the peak is made of.', ...
                'For the failing test: measure how far each of the seven', ...
                'peaks drops between the gain 50 file and the gain 20', ...
                'file, and check whether that separates anything at all.'};
        end

    case 4      % how strong is the 98.2 MHz station
        switch level
            case 1
                lines = { ...
                'Do the boring part first and do not skip it. Measure the', ...
                'two stations at N = 131072, then 32768, then 4096, then', ...
                '2048, and write all four rows down before you think', ...
                'about what they mean.', ...
                'The radio did not change between those four rows. Watch', ...
                'what your answer does anyway.'};
            case 2
                lines = { ...
                'Your table wobbles because you are reading the height of', ...
                'ONE FFT point. The FFT only measures a fixed comb of', ...
                'frequencies fs/N apart. If the station sits between two', ...
                'teeth of that comb, both teeth read low, and how low', ...
                'depends on N.', ...
                'So stop reading one point. Use ALL the points the', ...
                'station occupies - the whole channel - and add up the', ...
                'POWER in them.', ...
                'Day 1 rule, and people get this wrong every time:', ...
                '10*log10 for power, 20*log10 for voltage.'};
            case 3
                lines = { ...
                'The shape of the honest measurement:', ...
                '   X    = fftshift(fft(x));', ...
                '   fM   = (fc + (-n/2:n/2-1)*(fs/n))/1e6;', ...
                '   chan = abs(fM - 98.2) < 0.09;', ...
                '   pw   = 10*log10(sum(abs(X(chan)).^2)/n^2);', ...
                'Do that for 98.2 and again for 98.4, and subtract.', ...
                'Then repeat the whole thing at all four values of N.', ...
                'Notes: 0.09 not 0.10, so you stay clear of the', ...
                'neighbouring channel. The /n^2 matters - if your levels', ...
                'come out near +90 dB you have forgotten it.', ...
                'The number to report is the difference between the two', ...
                'stations, not either level on its own.'};
        end

    case 5      % which gain setting
        switch level
            case 1
                lines = { ...
                'Part (a) is bookkeeping, not cleverness:', ...
                '   total power = signal + noise.', ...
                'You can measure the total straight from the samples', ...
                'with mean(abs(x).^2). You can measure the noise from a', ...
                'piece of band that has nothing in it. Whatever is left', ...
                'over is signal.', ...
                'Do it for both files before you form an opinion.'};
            case 2
                lines = { ...
                'Two things that trip people up in part (a):', ...
                '  - the noise level you measure in the quiet band is per', ...
                '    FFT point. There are numel(x) points across the', ...
                '    whole span, so multiply before you subtract.', ...
                '  - the peak you exposed in Challenge 3 is not signal', ...
                '    and it is not receiver noise either. Decide what to', ...
                '    do with it and say what you decided.', ...
                'For part (b), the second number you need is max(abs(x))', ...
                'in each file. The radio cannot represent a sample bigger', ...
                'than 1.0.'};
            case 3
                lines = { ...
                'The shape of part (a), run once per file:', ...
                '   P    = (abs(fftshift(fft(x)))/numel(x)).^2;', ...
                '   tot  = sum(P);', ...
                '   pnb  = median(P(quiet));', ...
                '   nois = pnb*numel(P);', ...
                '   sig  = tot - nois;', ...
                '   pct  = 100*sig/tot;', ...
                'Check tot against mean(abs(x).^2). They should agree -', ...
                'if they do not, your normalising is wrong.', ...
                'Headroom in dB is  -20*log10(max(abs(x))).', ...
                'For (b) and (c) there is no formula. Put a clarity', ...
                'number and a headroom number in the same sentence and', ...
                'the answer writes itself.'};
        end

    case 6      % how busy is this band
        switch level
            case 1
                lines = { ...
                'The regulator asked for a rule, not a number. Read the', ...
                'three rules in the file and predict, before computing', ...
                'anything, which one will give the biggest count and', ...
                'which the smallest.', ...
                'Then compute all three. If your prediction was wrong,', ...
                'that is the most useful thing that will happen to you', ...
                'this afternoon.'};
            case 2
                lines = { ...
                'Two of the three rules only ask "is there something big', ...
                'here". One of them asks "does this slot carry any', ...
                'information".', ...
                'Before you decide which count to sign, go back to what', ...
                'you proved in Challenge 3 and ask which slot that peak', ...
                'lives in. Then look at which of your three rules keeps', ...
                'it and which throws it out.'};
            case 3
                lines = { ...
                'For each of the ten slot centres, build the window', ...
                '   w = abs(f_MHz - centre) < 0.1;', ...
                'and compute three quantities:', ...
                '   pk  = max(S_dB(w));                  tallest point', ...
                '   P   = (abs(fftshift(fft(iq)))/N).^2; power per point', ...
                '   cp  = 10*log10(sum(P(w)));           whole slot', ...
                'and the noise power in a slot of that width is', ...
                '   nref = 10*log10(median(P(quiet))*sum(w));', ...
                'Rule A compares pk with the noise floor.', ...
                'Rule B compares cp with nref.', ...
                'Rule C is rule A plus the condition cp - pk >= 3.', ...
                'Write the three counts in a table, then argue.'};
        end

    case 7      % the mystery capture
        switch level
            case 1
                lines = { ...
                'There is no single measurement that answers this. Work', ...
                'through the six questions in order and write one', ...
                'sentence for each.', ...
                'As you go, keep a note of WHICH evidence each sentence', ...
                'rests on. You will need that list for question 6, which', ...
                'is really a question about evidence you do not have.'};
            case 2
                lines = { ...
                'Questions 1 to 3 use tools you already built. The peak', ...
                'positions give you the spacing. The shape around a peak', ...
                'gives you the width, and tells you whether the power is', ...
                'in the carrier or in the sidebands - that is what', ...
                'separates AM from FM.', ...
                'Question 4 is a comparison: broadcast channels are wide', ...
                'and far apart, voice radio channels are narrow and close', ...
                'together. Which does this look like?', ...
                'Question 6: ask yourself what, inside a list of complex', ...
                'samples, could possibly carry an absolute frequency.'};
            case 3
                lines = { ...
                'Measurements worth making:', ...
                '  - the gaps between the peaks in kHz, and whether every', ...
                '    gap is a whole multiple of one number;', ...
                '  - the width of the strongest signal at 30 dB below its', ...
                '    own peak;', ...
                '  - what fraction of the channel power sits in the', ...
                '    single tallest point.', ...
                'For question 6, do not just say no. Name the three', ...
                'things that would let you answer it: receiver metadata,', ...
                'a transmitter of known frequency inside the capture, or', ...
                'a second capture at a deliberately different tuning.', ...
                'Then say which of those you have.', ...
                'Finally rerun the report on lo.iq and mark every', ...
                'conclusion survived or collapsed.'};
        end
end
end
